### ISSUE TITLE
Simulator returns incorrect value for /vehicle/steering_report

### ISSUE THREAD

**Issue by J-Rojas** [udacity/CarND-Capstone#110]
The message for the topic /vehicle/steering_report is a dbw_mkz_msgs/SteeringReport.

The simulator is returning the steering angle in radians within the `steering_wheel_angle_cmd` member. However this value should be the steering wheel angle which is multiplied by the steering wheel ratio. This would make these reports match the input provided by the SteeringCmd message.

The simulator is incorrect whereas Carla's SteeringReport values for this field match the intended value of the steering wheel angle.

**Comment by UAnjali** [comment]
Hey @J-Rojas,
I know this is too late to respond, can you raise a pull request on the simulator [repository](https://github.com/udacity/self-driving-car-sim)?
