### ISSUE TITLE
Simulator `steer_ratio` is incorrect. It should be 18.3345

### ISSUE THREAD

**Issue by J-Rojas** [udacity/CarND-Capstone#111]
The evidence for this is related to issue #110. 

The /vehicle/steering_report returns the steering angle in radians, based upon the range of these values being [-0.447241, 0.447241] which is close to 25.62 degrees. I assume this is the correct maximum steering angle that can be actuated as most cars would have a ~40 degree steering angle.

If the above assumption is true, the SteeringCmd.steering_wheel_angle_cmd values are about ~18.33x the values output by SteeringReport.steering_wheel_angle_cmd. I've tested this with a few different values and it holds true for all valid steering angles.

**Comment by UAnjali** [comment]
Responded on #110.
