### ISSUE TITLE
Simulator refuses to run. "There is no data folder"

### ISSUE THREAD

**Issue by ricgu8086** [udacity/CarND-Capstone#129]
Hi, the simulator worked the previous days, but after updating docker version (and its dependencies), it refuses to run:

```bash
ricardo@Mahou:~/Descargas/linux_sys_int$ ./system_integration.x86_64 
Set current directory to /home/ricardo/Descargas/linux_sys_int
Found path: /home/ricardo/Descargas/linux_sys_int/system_integration.x86_64
There is no data folder
ricardo@Mahou:~/Descargas/linux_sys_int$ 
```
It doesn't show anymore the configuration dialog.

Just for clarification, I'm not running the simulator in docker. I just mention it because this is what has changed in my computer from yesterday (simulator working) to today (simulator not working). I guess there are some dependencies that has been updated and broke whatever is needed by the simulator.

Any tip?

Thank you very much

**Comment by AnkurSatya** [comment]
I ran into the same problem. Install the simulator from [here ](http://video.udacity-data.com.s3.amazonaws.com)and run the **Default Linux desktop Universal.x86_64** directly(double click).
It worked for me!

**Comment by mvirgo** [comment]
Looks like above may have been solved; we've also now moved the project into a workspace to avoid configuration issues.
