### ISSUE TITLE
Communication Issue with Simulator in MacOSX and VirtualBox

### ISSUE THREAD

**Issue by Daniel-Prado** [udacity/CarND-Capstone#132]
Several students and I too have experienced an issue with the simulator running in Mac and ROS in the VirtualBox VM, the car does not move, despite publishing valid messages in throttle_cmd, and with the port forwarding correctly setup. This has been reported in the forums here:
https://discussions.udacity.com/t/car-freezes-in-simulator-solved/363942

Apparently, the issue is solved by modifying the /src/styx/server.py file as explained [here](https://discussions.udacity.com/t/car-freezes-in-simulator-solved/363942/12)

**Comment by swwelch** [comment]
Thanks! We've updated the simulator and the repo to address this problem.
