### ISSUE TITLE
Please document the units

### ISSUE THREAD

**Issue by ibrahim-mo** [udacity/CarND-Capstone#146]
It's not clear to me if the velocity units are in mph, k/h, or m/s?! Same goes with the constants defined in dbw_node.py. The units should not be ambiguous!

**Comment by UAnjali** [comment]
Hi @ibrahim-mo,
Though we are a little delayed in responding. In the DBW node lesson, you will find this line for the unit ambiguity
"Additionally, although the simulator displays speed in mph, all units in the project code use the metric system, including the units of messages in the /current_velocity topic (which have linear velocity in m/s)".
Thank you
