### ISSUE TITLE
should give an instruction on how to verify controller is right or not, with rosbag.

### ISSUE THREAD

**Issue by asimay** [udacity/CarND-Capstone#186]
should give an instruction on how to verify PID controller is right or not, with rosbag.

![image](https://user-images.githubusercontent.com/8703449/37756646-3d58465e-2de5-11e8-9c41-04e778fbdf75.png)

the value of brake obviously is not right from rosbag if brake is based on torque(N*m), because the value from rosbag is too small, if `Torque = a* m * r,` it should not be so small of column actual.

**Comment by asimay** [comment]
there is bug in test file and rosbag.
from test rosbag, I echo `/actual/brake_cmd`, output is:

![image](https://user-images.githubusercontent.com/8703449/37757582-847ee896-2de8-11e8-9400-184704fba703.png)

the pedal_cmd_type is 2, not torque. so the test_dbw.py has wrong.

**Comment by UAnjali** [comment]
Hi @asimay,
We suggest you refer to the Knowledge hub and reach out to your assigned mentor for user-specific issues. 
Thanks
