### ISSUE TITLE
missing some specific topic in simulator env.

### ISSUE THREAD

**Issue by asimay** [udacity/CarND-Capstone#187]
in example code, gave us some variables about vehicle to calculate the speed, accceleration, throttle, and also gave gas/fuel realted variables, but in simulation env, missing the fuel_report topic, which is used for fetcth the fuel container, but in real env,  it is there.

**Comment by asimay** [comment]
we need to subscribe ` /fuel_level_report`, if no this variable in simulator, it is hanging there.

**Comment by UAnjali** [comment]
Hi @asimay 
Though we are a little late to respond, we suggest you go through the DBW walkthrough video where you will get the required information on the fuel capacity concept.
Thanks
