### ISSUE TITLE
wp_yaw_const.csv problem

### ISSUE THREAD

**Issue by ahuer2435** [udacity/CarND-Capstone#203]
I find the values in wp_yaw_const.csv are not latitude and longitude coordinates. What do these data mean in wp_yaw_const.csv ？ How to calculate them from  latitude and longitude coordinates?

**Comment by UAnjali** [comment]
Hi @ahuer2435,
Though we are a little late to respond, we suggest you take a look at this [issue](https://github.com/udacity/CarND-Capstone/issues/31). 
Thanks
