### ISSUE TITLE
Please clarify the use of /vehicle/traffic_lights

### ISSUE THREAD

**Issue by carlosgalvezp** [udacity/CarND-Capstone#21]
@ckirksey3 wrote this on Slack :

```
Carlos Galvez [4 days ago] 
@caleb Thanks! So if I understand correctly, we should always subscribe to `/vehicle/traffic_lights`. The only difference between simulator and real life, is that we will *not* get the status of the light in the test track. Is that correct? In other words, we will *always* get `(x, y, z, yaw)` of the traffic light both in test track and simulator?

Caleb Kirksey [3 days ago] 
@carlosgalvezp Yes, exactly
```

However the documentation in `tl_detector` and Udacity's project description are not aligned with that statement:

        '''
        /vehicle/traffic_lights helps you acquire an accurate ground truth
        data source for the traffic light classifier, providing the location
        and current color state of all traffic lights in the simulator.
        This state can be used to generate classified images or subbed into
        your solution to help you work on another single component of the node.
        This topic won't be available when testing your solution in real life
        so don't rely on it in the final submission.
        '''

Therefore: could this be officially clarified?

**Comment by nikidimi** [comment]
Also, could you please update the documentation - this is an important information and it is only available in a Slack message that will get lost in time.

**Comment by ckirksey3** [comment]
Updated https://github.com/udacity/CarND-Capstone/commit/f2e915758f3a1bdc5655c6ef013fcd2b339d4cf0
