### ISSUE TITLE
Transformation between `/world/` and `/base_link` not available in rosbags

### ISSUE THREAD

**Issue by carlosgalvezp** [udacity/CarND-Capstone#24]
This transformation is currently provided by `bridge.py`, using the `TransformBroadcaster` class.

However, in `site.launch`, `bridge.py` is not included and the rosbags don't seem to have _any_ `/tf` information at all. You can easily check with:

    rosrun tf view_frames
    evince frames.pdf

The result is that the `tf` tree is empty.

Thus the provided code in `tl_detector` does not work because it tries to listen to the transformation between `/world` and `/base_link` which does not exist...

**Comment by ChrisShepherd81** [comment]
Is there any update? This is an blocking issue.

**Comment by ckirksey3** [comment]
Today is my last day working for Udacity so I wanted to share my progress on this and hopefully another engineer will carry on the work. Currently there is a [bag file](https://drive.google.com/file/d/0B2_h37bMVw3iMDNteHVvR1NHQ0E/view?usp=sharing) with the correct transform, but the car isn't stopping for red lights in the bag so I didn't want to share it on the same repo. Hopefully this bag will be useful for those who are stuck and Udacity can quickly get another bag uploaded in which light detection works correctly.

**Comment by J-Rojas** [comment]
I've been researching this issue and can confirm the rosbag provided by Caleb has the /world and /base_link and /world to /camera transforms. However the /camera transformation doesn't appear to accurately line up with objects in the world. There's some offsets for yaw, pitch, and roll that need to be incorporated if you are using this for traffic light detection using the camera projection.

**Comment by UAnjali** [comment]
We have launched a fresh new version of this Nanodegree in Q3 2021 which doesn't have the issues mentioned above. So, closing this issue.
