### ISSUE TITLE
[unity_simulator-3] process has died

### ISSUE THREAD

**Issue by Amin-Tgz** [udacity/CarND-Capstone#243]
Hi,
I have installed docker and went until `roslaunch launch/styx.launch` step
but when i enter this step terminal get-back this error

OS: Ubuntu 16.04 - x64
 ```
auto-starting new master
process[master]: started with pid [1427]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f11fe186-b77b-11e8-8226-0242ac110002
process[rosout-1]: started with pid [1440]
started core service [/rosout]
process[styx_server-2]: started with pid [1456]
process[unity_simulator-3]: started with pid [1458]
/capstone/ros/src/styx/unity_simulator_launcher.sh: line 19: sudo: command not found
process[dbw_node-4]: started with pid [1463]
process[waypoint_loader-5]: started with pid [1465]
process[pure_pursuit-6]: started with pid [1466]
```
**[unity_simulator-3] process has died [pid 1458, exit code 127, cmd /capstone/ros/src/styx/unity_simulator_launcher.sh __name:=unity_simulator __log:=/root/.ros/log/f11fe186-b77b-11e8-8226-0242ac110002/unity_simulator-3.log].**
```
log file: /root/.ros/log/f11fe186-b77b-11e8-8226-0242ac110002/unity_simulator-3*.log
process[waypoint_updater-7]: started with pid [1467]
process[tl_detector-8]: started with pid [1476]
(1456) wsgi starting up on http://0.0.0.0:4567
```

**Comment by lewisHome** [comment]
Same error here - did you find out what caused it

**Comment by Amin-Tgz** [comment]
unfortunately Not
you can use **Airsim** or **CARLA** instead of this simulator

**Comment by ZucchiniTang** [comment]
I meet this problem too, I don't know the reason. 
But I clicked 'reset data' of workspace, and then just upload and run your code, the error disappeared.
Can someone explain the reason?

**Comment by omarkhaledauto** [comment]
I commented the line #19 in unity_simulator_launcher.sh and the error disappeared, it now says 

[unity_simulator-3] process has finished cleanly
log file ...

However, it's not working yet but the error is no longer here.

**Comment by UAnjali** [comment]
Hi @Amin-Tgz,
Though we are a little late to respond, this issue has already been addressed in a knowledge hub thread we suggest you visit this [link ](https://knowledge.udacity.com/questions/9092)to reach out to Udacity support. 
Thanks
