### ISSUE TITLE
Can't install rosbag

### ISSUE THREAD

**Issue by scifiss** [udacity/CarND-Capstone#247]
I use the Udacity provided VM to develop the project. It shows the rosbag is not installed: The program 'rosbag' is currently not installed. You can install it by typing:
sudo apt install python-rosbag. When I do this, it shows "some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming". It also shows "unable to correct problems"

**Comment by UAnjali** [comment]
Hey @scifiss,
You can find the testing instructions using bag over here: https://github.com/udacity/CarND-Capstone/blob/master/ros/src/twist_controller/dbw_test.py
Thank you
