### ISSUE TITLE
The Simulator Environment Is In Black 

### ISSUE THREAD

**Issue by alchemz** [udacity/CarND-Capstone#265]
![sim](https://user-images.githubusercontent.com/10191088/48972989-c3227080-efea-11e8-8996-832acd393938.jpg)

I am using the Udacity VM. My friend can view the simulator normally in Ubuntu.

**Comment by mvirgo** [comment]
Hi there! Is this in the actual virtual machine or in the in-classroom workspace? Also, can you please share what OS you are using, as well as any CPU/GPU info that might be helpful.

**Comment by thomasdunlap** [comment]
I have the same problem on the virtual machine.  I have 3 CPUs and 8 GB RAM devoted to the VM.  My computer is Ubuntu 18.04, Intel i5 7th Gen with an NVIDIA GeForce GTX 1050 Ti.  The simulator works fine on my local computer, but doesn't work correctly on the Udacity VM.

**Comment by UAnjali** [comment]
Hi @alchemz,
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime in and new students can also learn from the discussion thread. 
Thank you
