### ISSUE TITLE
Catkin_make failed

### ISSUE THREAD

**Issue by Yunying-Chen** [udacity/CarND-Capstone#267]
I installed ROS Kinetic and Dataspped DBW on Ubuntu 16.04.  I tried to make and run this repository without any changes, but it showed the error as follows:

Base path: /media/pixel/intelssd1TB/Cap/carnd_capstone/ros
Source space: /media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src
Build space: /media/pixel/intelssd1TB/Cap/carnd_capstone/ros/build
Devel space: /media/pixel/intelssd1TB/Cap/carnd_capstone/ros/devel
Install space: /media/pixel/intelssd1TB/Cap/carnd_capstone/ros/install
####
####
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /media/pixel/intelssd1TB/Cap/carnd_capstone/ros/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /media/pixel/intelssd1TB/Cap/carnd_capstone/ros/build/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.14
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 8 packages in topological order:
-- ~~  - camera_info_publisher
-- ~~  - styx
-- ~~  - styx_msgs
-- ~~  - twist_controller
-- ~~  - waypoint_follower
-- ~~  - waypoint_loader
-- ~~  - waypoint_updater
-- ~~  - tl_detector
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'camera_info_publisher'
-- ==> add_subdirectory(camera_info_publisher)
-- +++ processing catkin package: 'styx'
-- ==> add_subdirectory(styx)
-- +++ processing catkin package: 'styx_msgs'
-- ==> add_subdirectory(styx_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- styx_msgs: 4 messages, 0 services
-- +++ processing catkin package: 'twist_controller'
-- ==> add_subdirectory(twist_controller)
-- +++ processing catkin package: 'waypoint_follower'
-- ==> add_subdirectory(waypoint_follower)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'waypoint_loader'
-- ==> add_subdirectory(waypoint_loader)
-- +++ processing catkin package: 'waypoint_updater'
-- ==> add_subdirectory(waypoint_updater)
-- +++ processing catkin package: 'tl_detector'
-- ==> add_subdirectory(tl_detector)
-- Configuring done
-- Generating done
-- Build files have been written to: /media/pixel/intelssd1TB/Cap/carnd_capstone/ros/build
####
####
Scanning dependencies of target std_msgs_generate_messages_lisp
Scanning dependencies of target std_msgs_generate_messages_nodejs
Scanning dependencies of target geometry_msgs_generate_messages_eus
Scanning dependencies of target geometry_msgs_generate_messages_lisp
Scanning dependencies of target _styx_msgs_generate_messages_check_deps_TrafficLight
Scanning dependencies of target sensor_msgs_generate_messages_lisp
Scanning dependencies of target _styx_msgs_generate_messages_check_deps_TrafficLightArray
Scanning dependencies of target _styx_msgs_generate_messages_check_deps_Lane
Scanning dependencies of target sensor_msgs_generate_messages_eus
Scanning dependencies of target sensor_msgs_generate_messages_nodejs
Scanning dependencies of target _styx_msgs_generate_messages_check_deps_Waypoint
Scanning dependencies of target std_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_lisp
Scanning dependencies of target geometry_msgs_generate_messages_nodejs
Scanning dependencies of target geometry_msgs_generate_messages_cpp
Scanning dependencies of target sensor_msgs_generate_messages_py
Scanning dependencies of target sensor_msgs_generate_messages_cpp
Scanning dependencies of target std_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_eus
Scanning dependencies of target std_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_cpp
Scanning dependencies of target geometry_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target _styx_msgs_generate_messages_check_deps_Lane
[  0%] Built target _styx_msgs_generate_messages_check_deps_TrafficLightArray
[  0%] Built target _styx_msgs_generate_messages_check_deps_TrafficLight
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target _styx_msgs_generate_messages_check_deps_Waypoint
[  0%] Built target std_msgs_generate_messages_py
Scanning dependencies of target styx_msgs_generate_messages_eus
Scanning dependencies of target styx_msgs_generate_messages_nodejs
Scanning dependencies of target styx_msgs_generate_messages_lisp
Scanning dependencies of target styx_msgs_generate_messages_py
Scanning dependencies of target styx_msgs_generate_messages_cpp
[ 18%] Built target styx_msgs_generate_messages_py
[ 33%] Built target styx_msgs_generate_messages_nodejs
[ 51%] Built target styx_msgs_generate_messages_eus
[ 66%] Built target styx_msgs_generate_messages_lisp
[ 81%] Built target styx_msgs_generate_messages_cpp
Scanning dependencies of target styx_msgs_generate_messages
Scanning dependencies of target libwaypoint_follower
[ 81%] Built target styx_msgs_generate_messages
[ 85%] Building CXX object waypoint_follower/CMakeFiles/libwaypoint_follower.dir/lib/libwaypoint_follower.cpp.o
[ 88%] Linking CXX shared library /media/pixel/intelssd1TB/Cap/carnd_capstone/ros/devel/lib/liblibwaypoint_follower.so
[ 88%] Built target libwaypoint_follower
Scanning dependencies of target pure_pursuit
[ 92%] Building CXX object waypoint_follower/CMakeFiles/pure_pursuit.dir/src/pure_pursuit_core.cpp.o
[ 96%] Building CXX object waypoint_follower/CMakeFiles/pure_pursuit.dir/src/pure_pursuit.cpp.o
[100%] Linking CXX executable /media/pixel/intelssd1TB/Cap/carnd_capstone/ros/devel/lib/waypoint_follower/pure_pursuit
CMakeFiles/pure_pursuit.dir/src/pure_pursuit.cpp.o: In function `void ros::Publisher::publish<geometry_msgs::TwistStamped_<std::allocator<void> > >(geometry_msgs::TwistStamped_<std::allocator<void> > const&) const':
/opt/ros/kinetic/include/ros/publisher.h:108: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
/opt/ros/kinetic/include/ros/publisher.h:108: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
/opt/ros/kinetic/include/ros/publisher.h:108: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
/opt/ros/kinetic/include/ros/publisher.h:112: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
/opt/ros/kinetic/include/ros/publisher.h:112: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
CMakeFiles/pure_pursuit.dir/src/pure_pursuit.cpp.o:/opt/ros/kinetic/include/ros/publisher.h:112: more undefined references to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)' follow
CMakeFiles/pure_pursuit.dir/src/pure_pursuit.cpp.o: In function `main':
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit.cpp:41: undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit.cpp:43: undefined reference to `ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit.cpp:44: undefined reference to `ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
CMakeFiles/pure_pursuit.dir/src/pure_pursuit.cpp.o: In function `param<bool>':
/opt/ros/kinetic/include/ros/node_handle.h:2122: undefined reference to `ros::NodeHandle::hasParam(std::string const&) const'
/opt/ros/kinetic/include/ros/node_handle.h:2124: undefined reference to `ros::NodeHandle::getParam(std::string const&, bool&) const'
CMakeFiles/pure_pursuit.dir/src/pure_pursuit.cpp.o: In function `main':
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit.cpp:48: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit.cpp:48: undefined reference to `ros::console::print(ros::console::FilterBase*, void*, ros::console::levels::Level, std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int, char const*)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit.cpp:52: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit.cpp:56: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit.cpp:65: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
CMakeFiles/pure_pursuit.dir/src/pure_pursuit.cpp.o: In function `ros::SubscriptionCallbackHelperT<boost::shared_ptr<geometry_msgs::TwistStamped_<std::allocator<void> > const> const&, void>::deserialize(ros::SubscriptionCallbackHelperDeserializeParams const&)':
/opt/ros/kinetic/include/ros/subscription_callback_helper.h:126: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
CMakeFiles/pure_pursuit.dir/src/pure_pursuit.cpp.o: In function `ros::SubscriptionCallbackHelperT<boost::shared_ptr<geometry_msgs::PoseStamped_<std::allocator<void> > const> const&, void>::deserialize(ros::SubscriptionCallbackHelperDeserializeParams const&)':
/opt/ros/kinetic/include/ros/subscription_callback_helper.h:126: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
CMakeFiles/pure_pursuit.dir/src/pure_pursuit.cpp.o:/opt/ros/kinetic/include/ros/subscription_callback_helper.h:126: more undefined references to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)' follow
CMakeFiles/pure_pursuit.dir/src/pure_pursuit_core.cpp.o: In function `waypoint_follower::PurePursuit::getCmdVelocity(int) const':
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:61: undefined reference to `ros::console::print(ros::console::FilterBase*, void*, ros::console::levels::Level, std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int, char const*)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:61: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
CMakeFiles/pure_pursuit.dir/src/pure_pursuit_core.cpp.o: In function `waypoint_follower::PurePursuit::calcLookaheadDistance(int)':
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:80: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
CMakeFiles/pure_pursuit.dir/src/pure_pursuit_core.cpp.o: In function `waypoint_follower::PurePursuit::calcCurvature(geometry_msgs::Point_<std::allocator<void> >) const':
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:100: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:100: undefined reference to `ros::console::print(ros::console::FilterBase*, void*, ros::console::levels::Level, std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int, char const*)'
CMakeFiles/pure_pursuit.dir/src/pure_pursuit_core.cpp.o: In function `waypoint_follower::PurePursuit::getNextWaypoint()':
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:291: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
CMakeFiles/pure_pursuit.dir/src/pure_pursuit_core.cpp.o: In function `waypoint_follower::PurePursuit::outputTwist(geometry_msgs::Twist_<std::allocator<void> >) const':
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:339: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
CMakeFiles/pure_pursuit.dir/src/pure_pursuit_core.cpp.o: In function `waypoint_follower::PurePursuit::go()':
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:358: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:388: undefined reference to `ros::console::print(ros::console::FilterBase*, void*, ros::console::levels::Level, std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int, char const*)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:352: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:355: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:370: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/src/waypoint_follower/src/pure_pursuit_core.cpp:388: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
collect2: error: ld returned 1 exit status
waypoint_follower/CMakeFiles/pure_pursuit.dir/build.make:338: recipe for target '/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/devel/lib/waypoint_follower/pure_pursuit' failed
make[2]: *** [/media/pixel/intelssd1TB/Cap/carnd_capstone/ros/devel/lib/waypoint_follower/pure_pursuit] Error 1
CMakeFiles/Makefile2:2094: recipe for target 'waypoint_follower/CMakeFiles/pure_pursuit.dir/all' failed
make[1]: *** [waypoint_follower/CMakeFiles/pure_pursuit.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

Does anyone know how to fix this?

**Comment by UAnjali** [comment]
Hi @Yunying-Chen,
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime in and new students can also learn from the discussion thread. 
You can also visit this thread for more information: classroom.udacity.com/nanodegrees/nd013/dashboard/overview
Thank you
