### ISSUE TITLE
SECURITY ISSUE: Insecure Flask Version Specified in `requirements.txt`

### ISSUE THREAD

**Issue by ser94mor** [udacity/CarND-Capstone#272]
GitHub complains about the version of Flask in `requirements.txt` claiming that it is insecure.
![image](https://user-images.githubusercontent.com/2496083/51116703-ed3f2480-181c-11e9-838c-5e288b4f9fdd.png)

Currently, the version of Flask is 0.11.1
![image](https://user-images.githubusercontent.com/2496083/51116815-31cac000-181d-11e9-98e0-7842fa610160.png)

**Comment by mvirgo** [comment]
@viennaharvey Can you look into whether we can upgrade this without any issues on Carla?

**Comment by UAnjali** [comment]
Hey @ser94mor,
Though we are late in responding, Flask is no longer there in requirement.txt.
Thank you.
