### ISSUE TITLE
providing executable for ARM 

### ISSUE THREAD

**Issue by Grillen80** [udacity/CarND-Capstone#274]
I'm currently working on a nvidia jetson tx1. Is there a chance that you provide the simulator compiled for arm architecture?

**Comment by mvirgo** [comment]
Hi there - 

I don't believe Unity allows you to compile the simulator for ARM from what I can tell, both from within Unity and from looking online, unfortunately.

**Comment by Grillen80** [comment]
Hey Michael,
thanks for your response. I'm trying hard to connect the simulator on my
compuer connected to the ROS on my nvidia jetson tx1 for the fina CarND-
Capstone Project.
I already set a comment on https://knowledge.udacity.com/questions/4017
with the follwing content.


I connected my host (ubuntu+simulator) with the ros_environment (nvidia
jetson arm) by using

ssh -L 4567:127.0.0.1:4567 nvidia@ip_address

But my connection fails after approx 40 seconds. I already used options like

-o ServerAliveCountMax=3 -o ServerAliveInterval=30

without success.

The errors seams to occur since there is no handshake between both devices.

Do you have any ideas ?

Am Mi., 16. Jan. 2019 um 01:02 Uhr schrieb Michael Virgo <
notifications@github.com>:

**Comment by UAnjali** [comment]
Hi @Grillen80,
Did you find any solution to your issue, please share so that other students can benefit?
Thank you
