### ISSUE TITLE
QUESTION: Versions of CUDA, CUDNN, TensorRT, GCC and Others

### ISSUE THREAD

**Issue by ser94mor** [udacity/CarND-Capstone#276]
What are the versions of:
- nvidia driver installed on Carla
- nvidia cuda
- nvidia cudnn
- nvidia TensorRT
- OpenCV
- does Carla have OpenMP and of what version?

I need this information because I consider using YOLO v3 for detection and classification of traffic signs. It is originally implemented using `darknet` neural networks framework which performs significantly faster than YOLO v3 converted to TensorFlow. I want to build a C shared library and include it into my submission. But for this, I need to know the versions of libraries I specified above.

**Comment by agneevguin** [comment]
Anyone got any idea on this?
I am trying to fine tune COCO training datasets for the traffic light detection but these are defined for Tensorflow >1.12.
However, the workspace and simulator provided uses Tensorflow 1.3
While trying to upgrade, I am facing issues with libcublas.so.9.0 or 10.0

Can I not use any models developed for tensorflow 4 or above?

**Comment by mvirgo** [comment]
Specific to these libraries, the simulator grader and Carla use the following:

|        | Simulator | Carla  |
| :-----------: |:-------------:| :-----:|
| Nvidia driver | 384.130 | 384.130 |
| CUDA | 8.0.61 | 8.0.61 |
| cuDNN | 6.0.21 | 6.0.21 |
| TensorRT | N/A | N/A |
| OpenCV | 3.2.0-dev | 2.4.8 |
| OpenMP | N/A | N/A |

Not sure why OpenCV is on two different versions, so we're going to investigate that further to make sure the two are lined up. There are no immediate plans to upgrade these, although eventually we will try to get TensorFlow, Keras and CUDA more up-to-date.
