### ISSUE TITLE
/current_pose is not updated rightly in Win10 Simulator

### ISSUE THREAD

**Issue by essamabas** [udacity/CarND-Capstone#294]
I am using the latest release - System Integration v1.3.
I noticed the /current_pose is not rightly updated.
1. It came too late - after 30 Seconds.
2. Even with using all possible-Modes the Manual/Camera - the received /current_pose is freezed and giving the same position - 
Please-Refer to my Recording: https://1drv.ms/v/s!AqwDyC2Wtzhnh9QFWEbFatrI0JLotQ

**Comment by UAnjali** [comment]
Hi @essamabas,
Though we are a little delayed in responding, we are unable to go through the shared video. Are you still facing this issue?
Thank you
