### ISSUE TITLE
Udacity CarND-Capstone, not receiving traffic from the simulation window

### ISSUE THREAD

**Issue by liupaladin** [udacity/CarND-Capstone#303]
I tried to put rospy. logwarn to see if the traffic information is import from the simulation window.  I put that in the traffic_cb node but there is nothing popped out. Would you please help me where should I put? My car doesn't stop at red light and I try to troubleshoot

**Comment by UAnjali** [comment]
Hi @liupaladin,
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime in and new students can also learn from the discussion thread. 
Thank you
