### ISSUE TITLE
CarND Capstone, image_cb is not called in tl_detector

### ISSUE THREAD

**Issue by liupaladin** [udacity/CarND-Capstone#304]
Can someone help me figure out why the image_cb is not called in tl_detector while the other is?

**Comment by naveedhd** [comment]
Have you made sure that `Camera` tickbox is checked in the simulator?

**Comment by UAnjali** [comment]
Hi @liupaladin,
Though we are a little late to respond, we encourage you to visit this thread: https://knowledge.udacity.com/questions/380497, so that our experienced mentors can chime in and new students can also learn from the discussion thread. 
Thank you
