### ISSUE TITLE
Sources for the simulator

### ISSUE THREAD

**Issue by ananevans** [udacity/CarND-Capstone#305]
I am trying to locate the sources for the self-driving-car-simulator used in this project. I the github repository of the simulator it says the sources are in this repository(CarND-Capstone), but in the download page (https://github.com/udacity/CarND-Capstone/releases)  the source archives have the CarND-Capstone sources, not the simulator's.
Please explain how I can find the Capstone Simulator sources.

**Comment by mvirgo** [comment]
Hi there!

Unfortunately we are not able to provide the source code for the Capstone simulator, as certain assets used in the simulator (such as the Carla model) are not owned by Udacity.

**Comment by venkatace** [comment]
What would be the other option to use different simulator?

**Comment by endymioncheung** [comment]
@mvirgo  I understand you cannot provide the source code as you explained above. But would it possible to have Udacity to provide the simulator for the latest Mac OS Catalina?

**Comment by UAnjali** [comment]
FWIW, Here is the link to simulator: https://github.com/udacity/self-driving-car-sim
