### ISSUE TITLE
Could not test DBW by using dbw_test.rosbag.bag 

### ISSUE THREAD

**Issue by popov1212** [udacity/CarND-Capstone#308]
As the dbw_test.py has told: 
1.Use the downloaded bag file :"https://s3-us-west-1.amazonaws.com/udacity-selfdrivingcar/files/reference.bag.zip", rename it to 'dbw_test.rosbag.bag' and place it in the CarND-Capstone/data folder.
2.Type in "roscore" as link: https://pastebin.com/qKfe6DSj
3.Type in "roslaunch dbw_test.launch " as link: https://pastebin.com/2sz2PznS
But comes up an error:  https://pastebin.com/2sz2PznS, Could you help me?

**Comment by mutalie** [comment]
Hi.. I am facing the same problem. Were you able to fix this?

**Comment by UAnjali** [comment]
Hi @popov1212,
Though we are a little late to respond, this issue has already been addressed in a knowledge hub thread we suggest you visit this [link ](https://knowledge.udacity.com/questions/201980)to reach out to Udacity support. 
Thanks

**Comment by popov1212** [comment]
"a little late"? yes! Your so callded "a little" nearly two years!

And I has already graduate from the Udacity nearly two years! I just wonder if you are really serious to my issues!
Are your colleagues samely treat the students as you?  Please have sense of responsiblity for the students!
Thanks!










At 2021-09-19 23:57:09, "UAnjali" ***@***.***> wrote:

Hi @popov1212,
Though we are a little late to respond, this issue has already been addressed in a knowledge hub thread we suggest you visit this link to reach out to Udacity support.
Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by UAnjali** [comment]
Hi @popov1212,
You'll have a better experience this time. We are here to support you with an SLA.
Thank you
