### ISSUE TITLE
Yaw in `wp_yaw_const.txt` given in degrees, not radians

### ISSUE THREAD

**Issue by carlosgalvezp** [udacity/CarND-Capstone#31]
This is then passed to `tf.transformations.quaternion_from_euler` which expects radians.
We should not change the code to transform to radians, because `churchlot_with_cars.csv` is (presumably) correctly given in radians.

So: please re-generate `wp_yaw_const.txt` with the yaw in radians. It would also be nice to name it with `csv` extension, for consistency. 

Follow-up: if `wp_yaw.txt` is not being used, please remove it.

**Comment by Deborah-Digges** [comment]
This is frustrating. I've already tuned the PIDs in twist_controller with these values which probably implicitly does the conversion now. @ckirksey3  Please can you confirm what's going on with this inconsistency in yaw values for waypoints in the simulator and for carla?

**Comment by Deborah-Digges** [comment]
Or is it because the waypoints in `churchlot_with_cars.csv` don't go around a circular track that the yaw values are small in that file?

**Comment by carlosgalvezp** [comment]
As far as I know, churchlot_with_cars.csv is also a circular track (as seen in the rosbag), and the yaw values go from 0 to 2pi...

**Comment by ckirksey3** [comment]
Thanks for pointing this out. Addressed in @IanBoyanZhang's PR: https://github.com/udacity/CarND-Capstone/pull/41
