### ISSUE TITLE
SDK Workstation link on README is broken!

### ISSUE THREAD

**Issue by Horki** [udacity/CarND-Capstone#316]
Use this option to install the SDK on a workstation that already has ROS installed: One Line SDK Install (binary)

https://bitbucket.org/DataspeedInc/dbw_mkz_ros/src/81e63fcc335d7b64139d7482017d6a97b405e250/ROS_SETUP.md?fileviewer=file-view-default

returns 404
That link has no power here

**Comment by alberto139** [comment]
Noticed the same issue, but found the file here: https://bitbucket.org/DataspeedInc/dbw_mkz_ros/src/master/ROS_SETUP.md

**Comment by UAnjali** [comment]
Hi @Horki 
We have updated the link in readme. Thank you @alberto139 for the link.
Thank you.

**Comment by Horki** [comment]
@UAnjali that was fast 😳
