### ISSUE TITLE
Stop Lights Setup

### ISSUE THREAD

**Issue by timtobey** [udacity/CarND-Capstone#32]
The stop lights in the sim are hanging overhead. The lights in the course are on single poles ( if the test pictures provided are an accurate example).   Shouldn't the stop light setup in the sim match the lights used in the Carla testing course?  Obviously the difference will affect things like where to look for the light in the image returned form the camera.

**Comment by ckirksey3** [comment]
I understand that this difference in positions creates some added complication, but we've provided the 3D position of the lights in the `/vehicle/traffic_lights` topic so you should be able to use that to find the light in the image.
