### ISSUE TITLE
README doesn't specify Python version

### ISSUE THREAD

**Issue by bsirang** [udacity/CarND-Capstone#332]
The README does not specify which Python version is required...

I found that the VM provided had python2.7 and pip (for python 2.7) installed. The VM also had Python 3.5 (without pip3)...

My first attempt at following the README led me to run pip install -r requirements.txt under a Python2.7 environment

**Comment by bsirang** [comment]
Actually now finding that it is supposed to be Python 2.7, but pip install -r requirements.txt chokes on setuptools in the VM...

Found some guidance on updating pip and then first installing a specific version of setuptools before installing requirements.txt: https://knowledge.udacity.com/questions/196688

Anyway, calling out Python2.7 in the README would be helpful.

**Comment by aadeshnpn** [comment]
@bsirang My understanding is that ros version used for the project only support python2.7. There are ways to use python3 but some packages might break.

**Comment by UAnjali** [comment]
Hi @bsirang,
We hope that https://knowledge.udacity.com helped you in resolving the issue.
Thank you
