### ISSUE TITLE
roslaunch launch/styx.launch throws and error when starting the first time with an error on engineio

### ISSUE THREAD

**Issue by hurtadosanti** [udacity/CarND-Capstone#342]
When installing the requirements.txt it will install the latest python-engineio as a dependency from python-socketio.

Adding to the requirements.txt the following line before python-socketio will fix the issue.
       
                python-engineio==3.11.2

**Comment by syedtaqi95** [comment]
I had the same issue, thanks for the workaround!

**Comment by hurtadosanti** [comment]
Merged into master
