### ISSUE TITLE
mac_sys_int v1.3 doesn't seem to work with macOS Catalina

### ISSUE THREAD

**Issue by cfezequiel** [udacity/CarND-Capstone#344]
I tried running the System Integration v1.3 simulator on macOS v10.15.7 but it just generated the following error: "The application “sys_int” can’t be opened."

**Comment by anhdamm** [comment]
Did you fix it? I also had the same issue with you but I don't know how to open the Simulator on Mac. If you did, please tell me the instruction. Thank you so much!

**Comment by UAnjali** [comment]
Hi @cfezequiel,
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. And please go through this thread https://knowledge.udacity.com/questions/400765.
Thanks
