### ISSUE TITLE
Docker build fails - PIP + Python 2.7 EOL

### ISSUE THREAD

**Issue by JGalego** [udacity/CarND-Capstone#348]
Docker build fails after upgrading `pip` (**root cause:** newer versions of `pip` no longer support python 2.x)

> **DEPRECATION:** Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality. [source][1]

[1]: https://pip.pypa.io/en/latest/development/release-process/#python-2-support

The issue is described [here](https://stackoverflow.com/questions/65896334/python-pip-broken-wiith-sys-stderr-writeferror-exc)

**Quick fix:**

Replace `pip install --upgrade pip` 
with `pip install --upgrade "pip < 21.0"`

**Comment by ariesgun** [comment]
Thanks for this.
You should create a pull request asking them to merge this quick fix into the main repo.

**Comment by UAnjali** [comment]
Thanks for bringing this to our notice. We have changed the Dockerfile based on your suggestion.
