### ISSUE TITLE
Cannot resize the simulator window (on Mac OS X 10.11.x)

### ISSUE THREAD

**Issue by laventura** [udacity/CarND-Capstone#65]
Hello --

I am unable to resize the simulator window on Mac OS X 10.11.x.
It has taken over my entire Macbook display.
I cannot grab hold of the edges / corner of the window and resize it like any normal Mac program.

I've tried clicking on the green button, but it barely changes the size of the window. 

See below. 
Any pointers?? Greatly appreciated! Thanks!

<img width="1440" alt="screen shot 2017-09-28 at 3 56 36 pm" src="https://user-images.githubusercontent.com/419789/30993924-0f6f69b0-a466-11e7-8213-df90c0d7232c.png">

**Comment by mreichelt** [comment]
@laventura The simulator is not resizable. You have to press the `Alt` key immediately when starting the simulator program to get the settings dialog - there you can choose the resolution.
Please close this issue when your problem is resolved.

**Comment by laventura** [comment]
@mreichelt  
Thanks! That worked. 🙏🏻
Press ALT while opening the simulator --> gives an option to choose resolution. Managed to do that finally.
