### ISSUE TITLE
Fix CSV file of waypoints for the test track

### ISSUE THREAD

**Issue by carlosgalvezp** [udacity/CarND-Capstone#71]
They are specified in the wrong order, as discussed on Slack.
The only thing available to us is the rosbag `udacity_succesful_light_detection.bag`, from which we should listen to `/base_waypoints` and generate our own CSV file.

Please release an official CSV file, or update the documentation to point students on what to do.

**Comment by UAnjali** [comment]
Hi @carlosgalvezp 
Though we are a little delayed in responding, we hope that the issue was addressed in "[Fix waypoints at test site #72](https://github.com/udacity/CarND-Capstone/pull/72)"
