### ISSUE TITLE
Restart problem

### ISSUE THREAD

**Issue by shyam-jagannathan** [udacity/CarND-Capstone#82]
Hey guys, 

I have installed ROS Kinetic natively on Ubuntu 16.04 and also running the simulator natively. 
For the first time (say after OS reboot) I launch the styx.launch file which starts wsgi server on port 4567 as shown below,

core service [/rosout] found
process[styx_server-1]: started with pid **[3239]**
process[unity_simulator-2]: started with pid [3240]
What is the full path to your Unity simulator?
process[dbw_node-3]: started with pid [3244]
process[waypoint_loader-4]: started with pid [3245]
process[pure_pursuit-5]: started with pid [3246]
process[waypoint_updater-6]: started with pid [3249]
process[tl_detector-7]: started with pid [3263]
[INFO] [1507094692.698115]: --- throttle=0.0, brake=0.0, steer=0.0
[INFO] [1507094692.798314]: --- throttle=0.0, brake=0.0, steer=0.0
[INFO] [1507094692.898259]: --- throttle=0.0, brake=0.0, steer=0.0
[INFO] [1507094692.998241]: --- throttle=0.0, brake=0.0, steer=0.0
[INFO] [1507094693.098218]: --- throttle=0.0, brake=0.0, steer=0.0
[INFO] [1507094693.198182]: --- throttle=0.0, brake=0.0, steer=0.0
[INFO] [1507094693.298184]: --- throttle=0.0, brake=0.0, steer=0.0
**(3239) wsgi starting up on http://0.0.0.0:4567**
[INFO] [1507094693.398199]: --- throttle=0.0, brake=0.0, steer=0.0

And when I start the simulator, there is a successful connection between ros and simulator and the car drives around the track successfully.

Now when i close the ROS launch terminal by pressing CTRL+C the process ends, i exit the simulator also. But when I restart the ROS launch 2nd time, I dont see the message wsgi starting up. Now because of the simulator also does not connect. There is no  way for me to work around except rebooting my machine which is horrible.

What I noticed was, if I dont start the simulator and do a ROS launch then everytime I kill and relaunch wsgi starts successfully. I dont understand whats happening but found a thread on socket.io which is very similar to what I am observing. Can you _PLEASE_PLEASE_ take a look?

https://github.com/socketio/socket.io/issues/1602

**Comment by UAnjali** [comment]
Hi @shyam-jagannathan,
"Though we are a little late to respond, this issue has already been addressed in a knowledge hub thread we suggest you visit this [link ](https://knowledge.udacity.com/questions/17572)to reach out to Udacity support. 
Thanks"
